name: C/C++ Lint

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.c'
      - '**.cpp'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.c'
      - '**.cpp'

jobs:
  Code-Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
